### ISSUE TITLE
Questions about Sec.3.2, Guided Distillation

### ISSUE THREAD

**Issue by zjhJOJO** [G-U-N/Phased-Consistency-Model#25]
![issue](https://github.com/user-attachments/assets/07f80056-6d7f-4d2b-b149-cf7a5bb8f0d2). Could you please give me some insight? how to obtain this conclusion in Eq. (23) that satisfies for any t' <= t? Thank you very much.

**Comment by G-U-N** [comment]
Hi! Thank you for proposing the question. It is not a very strict expression indeed. What I want to express here is that we are actually letting the consistency model to learn the weighted integral (weighted summation) of epsilon prediction on the trajectory. So the learning target will be linearly influenced by the epsilon prediction of all $t' \in [s,t]$.
