### ISSUE TITLE
Training code for SDXL

### ISSUE THREAD

**Issue by youngwanLEE** [G-U-N/Phased-Consistency-Model#7]
Hi, 

I'm impressed by your amazing work !!

Do you plan to open the training code for SDXL? 

It would be helpful for the open-source community.

**Comment by G-U-N** [comment]
Hey @youngwanLEE. Definitely will release the training code for SDXL! So many things occupy my time currently, I will upload them later. Thank your for the attention!

**Comment by lovejing0306** [comment]
+1

**Comment by xiao2mo** [comment]
waiting for it.

**Comment by G-U-N** [comment]
Hi, guys. I have been working on Stable Diffusion 3 in the past few days. I have uploaded all the training scripts for it. I hope they will be helpful. The training scripts for SDXL will also be uploaded after verifying everything is okay.

**Comment by xiao2mo** [comment]
> Hi, guys. I have been working on Stable Diffusion 3 in the past few days. I have uploaded all the training scripts for it. I hope they will be helpful. The training scripts for SDXL will also be uploaded after verifying everything is okay.

SDXL waiting for it ^_^

**Comment by G-U-N** [comment]
I hope it will be quick. I am trying to apply for some GPUs for verifying before uploading.

**Comment by bengen-y** [comment]
looking forward to it ！！！

**Comment by xiao2mo** [comment]
looking forward to it ！！！

**Comment by xiao2mo** [comment]
looking forward to it ！！！

**Comment by xiao2mo** [comment]
looking forward to it ！！！

**Comment by G-U-N** [comment]
@xiao2mo . Thanks for the interest! Will upload it asap.

**Comment by xiao2mo** [comment]
> asap

😁

**Comment by xiao2mo** [comment]
> @xiao2mo . Thanks for the interest! Will upload it asap.
hi。

**Comment by xiao2mo** [comment]
looking forward to it ！！！

**Comment by youngwanLEE** [comment]
@G-U-N 
While waiting for your code, I have tried implementing PCM-SDXL. 
I wonder if the discriminator for SDXL has the same architecture as SD-v1.5.

**Comment by George0726** [comment]
I have trained PCM on my fine-tuned 9-channel outpainting SDXL. I found that 8-step is much better than 4-step that is different from Fig 7. in your paper. I am not sure if it is owing to the outpainting tasks or the convergence of my model.  I wonder if you can reveal your SDXL based architecture so that I can verify my current experiments.

**Comment by G-U-N** [comment]
Hey all, SORRY for the late update. I just got access to my original code on the GPU server.

The LoRA training script is now available at [run.sh](https://github.com/G-U-N/Phased-Consistency-Model/blob/master/code/text_to_image_sdxl/train_pcm_lora_sdxl.sh).

**Comment by G-U-N** [comment]
Typically 2k iterations is enough to see clear improvements. Yet I have no resources to retrain everything. LMK if you encounter any issues.

Best,
Fu-Yun

**Comment by G-U-N** [comment]
<img width="1098" alt="screen-shot" src="https://github.com/user-attachments/assets/5e9ff99c-c8a8-4a01-ab39-17395bd65816">

500 iter, 1000 iter, 1500 iter, 2000 iter with a batch size 40. Longer training make it better.

**Comment by George0726** [comment]
```
    accelerator.clip_grad_norm_(unet.parameters(), args.max_grad_norm)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 2101, in clip_grad_norm_
    self.unscale_gradients()
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 2064, in unscale_gradients
    self.scaler.unscale_(opt)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/amp/grad_scaler.py", line 325, in unscale_
    raise RuntimeError(
RuntimeError: unscale_() has already been called on this optimizer since the last update().
```
May I ask a question? Have you guys ever met this bug. It may caused by using twice clip_grad_norm for the discriminators and the generators separately. accelerator.clip_grad_norm_

**Comment by youngwanLEE** [comment]
I successfully reproduced PCM-SDXL and implemented PCM-KOALA models using [KOALA U-Net](https://youngwanlee.github.io/KOALA/) backbones.

I really appreciate your open-source effort.
